name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create build environmnent
        run: make O=../build BR2_EXTERNAL=../external -C ./buildroot bb_builder_defconfig

      - name: Build
        run: make -C build
